# Generated by Django 2.2.10 on 2020-04-13 19:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_main_1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pId', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('accountcode', models.IntegerField(default=0)),
                ('mainaccount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='costcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='قم بادخال اسم المركز المالي  ', max_length=100, unique=True, verbose_name='اسم المركز')),
                ('added_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transactionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebookNum', models.IntegerField(blank=True, null=True, verbose_name='الرقم الدفتري')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='البيان')),
            ],
        ),
        migrations.CreateModel(
            name='yearTBL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurentYear', models.IntegerField()),
                ('oldYear', models.IntegerField()),
                ('trannoclose', models.IntegerField()),
                ('trannoopen', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('branchName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='TranTableMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebookNum', models.IntegerField(blank=True, null=True, verbose_name='الرقم الدفتري')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='ملحوظة')),
                ('checkdate', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='تاريخ الشيك')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('TranNo', models.BigIntegerField(null=True, verbose_name='رقم القيد')),
                ('TranDate', models.DateTimeField(verbose_name='التاريخ')),
                ('Post', models.BooleanField(default=False, verbose_name='الترحيل')),
                ('Cate', models.CharField(max_length=2, null=True)),
                ('serial', models.IntegerField(null=True, verbose_name='رقم السند')),
                ('added_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('branchName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_app.branch')),
                ('yeartran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Finance.yearTBL')),
            ],
        ),
        migrations.CreateModel(
            name='TranTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurnaldesc', models.CharField(max_length=200, verbose_name='البيان')),
                ('TranAmount', models.FloatField(verbose_name='المبلغ')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('TranNo', models.BigIntegerField(default=0, verbose_name='رقم القيد')),
                ('AccountCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Finance.Account')),
                ('Ccenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Finance.costcenter')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tranTableMain', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Finance.TranTableMain')),
            ],
        ),
        migrations.CreateModel(
            name='transactiontbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('tranmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.transactionMaster')),
            ],
        ),
        migrations.CreateModel(
            name='tbcurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='-', max_length=100)),
                ('Singlname', models.CharField(blank=True, max_length=10, null=True)),
                ('collectionname', models.CharField(blank=True, max_length=20, null=True)),
                ('partname', models.CharField(blank=True, max_length=10, null=True)),
                ('Sympol', models.CharField(blank=True, max_length=10, null=True)),
                ('Cpartname', models.CharField(blank=True, max_length=15, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('equivalent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
