# Generated by Django 2.2.10 on 2020-04-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_ad1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trantable',
            name='TranAmount',
            field=models.FloatField(blank=True, null=True, verbose_name='المبلغ'),
        ),
    ]
