# Generated by Django 2.2.10 on 2020-04-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_auto_20200416_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trantable',
            name='Ccenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Finance.costcenter'),
        ),
    ]
