# Generated by Django 2.2.10 on 2020-04-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0007_hd2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trantablemain',
            name='TranNo',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='رقم القيد'),
        ),
    ]
