# Generated by Django 2.2.10 on 2020-04-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0008_hd3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trantablemain',
            name='Cate',
            field=models.CharField(blank=True, default=0, max_length=2),
            preserve_default=False,
        ),
    ]
