# Generated by Django 2.2.10 on 2020-04-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0009_hd01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='trantablemain',
            name='TranNo',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='رقم القيد'),
            preserve_default=False,
        ),
    ]
