# Generated by Django 2.2.10 on 2020-04-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecurityGuard', '0001_s001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='point',
        ),
        migrations.AlterField(
            model_name='time',
            name='Lat',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='time',
            name='Lon',
            field=models.FloatField(max_length=50),
        ),
    ]
