# Generated by Django 2.2.10 on 2020-05-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecurityGuard', '0003_s003'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='Present',
            field=models.BooleanField(default=False),
        ),
    ]
